// Generated by CoffeeScript 1.7.1

/*
Module dependencies.
 */

(function() {
  var app, contact, express, http, path, routes, user;

  express = require("express");

  app = express();

  app.locals.pretty = true;

  app.use(require("connect-assets")({
    buildDir: "public",
    helperContext: app.locals
  }));

  routes = require("./routes");

  user = require("./routes/user");

  contact = require("./routes/contact");

  http = require("http");

  path = require("path");

  app.set("port", process.env.PORT || 3000);

  app.set("views", path.join(__dirname, "views"));

  app.set("view engine", "jade");

  app.use(express.favicon());

  app.use(express.logger("dev"));

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(express.methodOverride());

  app.use(app.router);

  app.use(require("stylus").middleware(path.join(__dirname, "public")));

  app.use(express["static"](path.join(__dirname, "public")));

  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  app.get("/", routes.index);

  app.get("/about", user.list);

  app.get("/contact", contact.list);

  app.post("/contact", contact.form);

  http.createServer(app).listen(app.get("port"), function() {
    return console.log("Express server listening on port " + app.get("port"));
  });

}).call(this);
